name: Build release apk and publish

on:
  push:
#    tags:
#      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: build with Gradle
      env:
        ks: ${{ secrets.keystore }}
        ks_p: ${{ secrets.keystore_pass }}
        ka: ${{ secrets.key_alias }}
        k_p: ${{ secrets.key_pass }}
      run: |
        chmod +x gradlew
        echo $ks | base64 -d - >> ks
        sed -i \
            s/"release {"/"release {\\nstoreFile file\(\"ks\"\)\\nstorePassword System.getenv\(\'ks_p\'\)\\nkeyAlias System.getenv\(\'ka\'\)\\nkeyPassword System.getenv\(\'k_p\'\)"/ \
            app/build.gradle
        ./gradlew assembleRelease

    - uses: actions/upload-artifact@master
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - uses: actions/setup-ruby@v1.0.0

    - name: upload to Play Store
      env:
        gk: $${{ secrets.play_key }}
      run: |
        echo $gk | base64 -d - >> gk
        gem install fastlane -N
        fastlane supply --metadata_path fastlane/metadata/android --skip_upload_images true --skip_upload_screenshots true --apk app/release/app-release.apk \
                        --mapping app/build/outputs/mapping/release/mapping.txt --json_key gk --package_name com.github.moko256.twitlatte --validate_only
