name: Build release apk and publish

on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: build with Gradle
      run: |
        chmod +x gradlew
        sed -i s/-all./-bin./ gradle/wrapper/gradle-wrapper.properties
        exit 1 //TODO: add release key
        ./gradlew assembleRelease

    - uses: actions/setup-ruby@v1.0.0

    - name: upload to Play Store
      run: |
        gem install fastlane -N
        exit 1 //TODO: upload
